// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "GUI.h"
#include "GUICallbacks.h"

Fl_Double_Window *guiWindowApplicationMode=(Fl_Double_Window *)0;

Fl_Round_Button *radioButtonYellowPages=(Fl_Round_Button *)0;

static void cb_radioButtonYellowPages(Fl_Round_Button* o, void*) {
  onguiRadioButtonApplicationModeChanged(o);
}

Fl_Round_Button *radioButtonAgents=(Fl_Round_Button *)0;

static void cb_radioButtonAgents(Fl_Round_Button* o, void*) {
  onguiRadioButtonApplicationModeChanged(o);
}

static void cb_Start(Fl_Button*, void*) {
  onguiButtonStartApplication();
}

/**
 Selects the mode of the application
 - YellowPages
 - Agents
*/
Fl_Double_Window* make_window_select_mode() {
  { guiWindowApplicationMode = new Fl_Double_Window(216, 100, "SiSiMEX");
    { Fl_Group* o = new Fl_Group(5, 20, 205, 110, "Application Mode");
      o->align(Fl_Align(65));
      { radioButtonYellowPages = new Fl_Round_Button(5, 45, 205, 25, "YellowPages");
        radioButtonYellowPages->down_box(FL_ROUND_DOWN_BOX);
        radioButtonYellowPages->callback((Fl_Callback*)cb_radioButtonYellowPages);
        radioButtonYellowPages->align(Fl_Align(68|FL_ALIGN_INSIDE));
      } // Fl_Round_Button* radioButtonYellowPages
      { radioButtonAgents = new Fl_Round_Button(5, 20, 205, 25, "Agents");
        radioButtonAgents->down_box(FL_ROUND_DOWN_BOX);
        radioButtonAgents->value(1);
        radioButtonAgents->callback((Fl_Callback*)cb_radioButtonAgents);
        radioButtonAgents->align(Fl_Align(68|FL_ALIGN_INSIDE));
      } // Fl_Round_Button* radioButtonAgents
      { Fl_Button* o = new Fl_Button(5, 70, 205, 25, "Start Application");
        o->down_box(FL_UP_FRAME);
        o->selection_color(FL_FOREGROUND_COLOR);
        o->callback((Fl_Callback*)cb_Start);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(10, 105, 205, 30);
      o->end();
    } // Fl_Group* o
    guiWindowApplicationMode->size_range(216, 100);
    guiWindowApplicationMode->end();
    guiWindowApplicationMode->resizable(guiWindowApplicationMode);
  } // Fl_Double_Window* guiWindowApplicationMode
  return guiWindowApplicationMode;
}

Fl_Double_Window *guiWindowMultiagentApplication=(Fl_Double_Window *)0;

static void cb_List(Fl_Button*, void*) {
  onGuiButtonListLocalNodes();
}

static void cb_Inspect(Fl_Button*, void*) {
  onGuiButtonInspectLocalNode();
}

static void cb_Get(Fl_Button*, void*) {
  onguiButtonGetContributorsForItem();
}

static void cb_Quit(Fl_Button*, void*) {
  onGuiButtonQuitMultiagentApplication();
}

/**
 Main menu of the multi-agents application.
 It provides buttons to execute several actions.
*/
Fl_Double_Window* make_window_multiagents_application() {
  { guiWindowMultiagentApplication = new Fl_Double_Window(190, 181, "SiSiMEX Multi Agent Application");
    { Fl_Button* o = new Fl_Button(5, 5, 180, 25, "List local nodes");
      o->callback((Fl_Callback*)cb_List);
      o->align(Fl_Align(FL_ALIGN_CLIP));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(5, 30, 180, 25, "Inspect local node");
      o->callback((Fl_Callback*)cb_Inspect);
      o->align(Fl_Align(FL_ALIGN_CLIP));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(5, 55, 180, 25, "Get contributors for item");
      o->callback((Fl_Callback*)cb_Get);
      o->align(Fl_Align(FL_ALIGN_CLIP));
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(5, 85, 180, 60);
      o->end();
      Fl_Group::current()->resizable(o);
    } // Fl_Group* o
    { Fl_Button* o = new Fl_Button(5, 150, 180, 25, "Quit Multi Agent Application");
      o->callback((Fl_Callback*)cb_Quit);
      o->align(Fl_Align(FL_ALIGN_CLIP));
    } // Fl_Button* o
    guiWindowMultiagentApplication->end();
  } // Fl_Double_Window* guiWindowMultiagentApplication
  return guiWindowMultiagentApplication;
}

Fl_Double_Window *guiWindowYellowPagesApplication=(Fl_Double_Window *)0;

static void cb_Quit1(Fl_Button*, void*) {
  onGuiButtonQuitYellowPages();
}

/**
 Main menu of the yellowpages application.
*/
Fl_Double_Window* make_window_yellowpages_application() {
  { guiWindowYellowPagesApplication = new Fl_Double_Window(190, 48, "SiSiMEX Multi Agent Application");
    { Fl_Button* o = new Fl_Button(5, 5, 180, 25, "Quit Yellow Pages");
      o->callback((Fl_Callback*)cb_Quit1);
      o->align(Fl_Align(FL_ALIGN_CLIP));
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(5, 35, 180, 25);
      o->end();
      Fl_Group::current()->resizable(o);
    } // Fl_Group* o
    guiWindowYellowPagesApplication->end();
  } // Fl_Double_Window* guiWindowYellowPagesApplication
  return guiWindowYellowPagesApplication;
}
